name: test-github-action

run-name: pour apprendre github-action

on: [push]

jobs:
    run-app:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - run: yarn install

            - run: yarn run dev
