name: test-app

run-name: test-workflow

on: [push]

jobs:
  check-test-app:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - uses: action/node@v3
        with: 
        node-version: '18'
      -run: yarn install
